import React from 'react';
import { Sparkles, Activity } from 'lucide-react';
import { AssessmentResult } from '../../../types';
import DamageVisualizer from './DamageVisualizer';

interface AnalysisVisualsProps {
  imageUrl: string;
  result: AssessmentResult;
  visualizerRef: React.RefObject<HTMLDivElement>;
}

const AnalysisVisuals: React.FC<AnalysisVisualsProps> = ({ imageUrl, result, visualizerRef }) => {
  return (
    <div className="space-y-6 print-break-inside">
      {/* Main Image Analyzer */}
      <div className="bg-white rounded-2xl shadow-sm border border-surface-200">
        <div className="px-6 py-4 border-b border-surface-100 bg-surface-50/50 flex items-center justify-between rounded-t-2xl">
          <h2 className="text-lg font-bold text-surface-900">Damage Visualization</h2>
          <span className="text-xs font-medium px-2.5 py-1 bg-surface-200/50 text-surface-600 rounded-full border border-surface-200">
            {result.damages.length} Areas Detected
          </span>
        </div>

        {/* Added ref to wrapper for HTML2Canvas capture */}
        <div className="p-1" ref={visualizerRef}>
          <DamageVisualizer imageUrl={imageUrl} damages={result.damages} />
        </div>
      </div>

      {/* AI Summary Card */}
      <div className="bg-gradient-to-br from-white to-surface-50 rounded-2xl shadow-sm border border-surface-200 p-6 relative overflow-hidden group">
        <div className="absolute top-0 right-0 w-32 h-32 bg-brand-50/50 rounded-bl-full -mr-8 -mt-8 transition-transform group-hover:scale-110" />

        <div className="relative">
          <div className="flex items-center gap-3 mb-4">
            <div className="p-2 bg-brand-100 rounded-xl shadow-inner">
              <Sparkles className="w-5 h-5 text-brand-600" />
            </div>
            <div>
              <h3 className="text-lg font-bold text-surface-900">AI Assessment Analysis</h3>
              <p className="text-xs text-surface-500">Generated by Hero Vida AI Model</p>
            </div>
          </div>

          <div className="prose prose-sm text-surface-600 leading-relaxed mb-6">
            <p>{result.summary}</p>
          </div>

          <div className="flex items-center justify-between pt-4 border-t border-surface-200/60">
            <div className="flex items-center gap-2 text-sm text-surface-500">
              <Activity className="w-4 h-4" />
              <span>Model Confidence</span>
            </div>

            <div className="flex items-center gap-3">
              <div className="w-24 h-2 bg-surface-100 rounded-full overflow-hidden shadow-inner">
                <div
                  className={`h-full rounded-full transition-all duration-1000 ${result.confidenceScore > 0.8 ? 'bg-emerald-500' :
                    result.confidenceScore > 0.5 ? 'bg-amber-500' : 'bg-red-500'
                    }`}
                  style={{ width: `${result.confidenceScore * 100}%` }}
                />
              </div>
              <span className="font-mono font-bold text-surface-900">{(result.confidenceScore * 100).toFixed(0)}%</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default AnalysisVisuals;
